name: Push branch to GitHub and test

on:
  # Allow this workflow to be called from other workflows.
  workflow_call:

  # Trigger analysis when pushing in main or pull requests, and when creating
  # a pull request.
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud:
    name: Run tests, linting and sonar analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute tests
        run: fastlane test
