name: Push branch to GitHub and test

on:
  # Allow this workflow to be called from other workflows.
  workflow_call:

  # Trigger analysis when pushing in main or pull requests, and when creating
  # a pull request.
  workflow_dispatch:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  sonarcloud:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - run: |
            cd ../..
            bundle exec rake
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute tests
        run: bundle exec fastlane test
